### ISSUE TITLE
Vol 1 Introduction section

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PDQm#17]
MHD Vol 1 dropdown menu contains an entry for the introduction section.   It goes to MHD Home, which contains the contents of ITI TF-1: 33. 

Do this for PDQm.

**Comment by DavidPyke** [comment]
I'm not sure the value of having a defined link to the home page on the menu and a link under volume 1.  Can you explain that a bit more?

**Comment by JohnMoehrke** [comment]
@DavidPyke see what PIXm did. They just have one file for all of Volume 1, with links so that each H2 can be indicated. The layout on the index.html helps the reader see the major sections of the IG including the H2 in Volume 1. This index.htm layout can be supported by indepenendant pages or deep links to one page.

I have added an open issue. I don't want to change PDQm this late for this particular issue. Open issue indicates we might make the cange as part of the resolution.

**Comment by JohnMoehrke** [comment]
yes, will do.
